"use strict";

const app = document.querySelector("#game");
const toast = document.querySelector("#toast");
const STORAGE_KEY = "roundhouse.euchre.progress.v2";
const SUITS = ["♣", "♦", "♥", "♠"];
const RED = new Set(["♦", "♥"]);
const RANKS = ["9", "10", "J", "Q", "K", "A"];
const FACE_PORTRAITS = { J: ["01", "06", "13", "17"], Q: ["03", "08", "14", "16"], K: ["02", "04", "12", "18"] };
const BENNY_PORTRAIT = "../poison/assets/portraits/12.png";
const LEVELS = [
  ["Meet the Pack","Which cards do we use?",20,"pack"],["Trump Power","Why trump beats other suits",25,"trump"],["The Right Bower","The strongest ordinary card",30,"right"],["The Left Bower","The sneaky jack that changes suit",35,"left"],["Meet the Benny","The Joker rules them all",35,"benny"],["Follow Suit","Play legal cards",40,"follow"],["Win the Trick","Spot the strongest card",45,"winner"],["Save Your Trump","A first tactical choice",50,"tactics"],["Round One Bidding","Order up the turned card",55,"orderup"],["Dealer Picks Up","What ordering up changes",55,"dealerpick"],["Round Two Bidding","Call a different suit",60,"roundtwo"],["Going Alone","Drop your partner when your hand is huge",65,"alone"],["Scoring","Earn 1, 2 or 4 points",65,"scoring"],["Help Your Partner","Don't steal a trick unnecessarily",65,"partner"],["Lead for Your Partner","Set up your team",70,"partnerlead"],["Mini Mission","Make three smart team plays",80,"mini"],["Roundhouse Table","Play a full five-trick hand",120,"full"]
].map((x,i)=>({id:i+1,title:x[0],subtitle:x[1],xp:x[2],kind:x[3]}));
const ACHIEVEMENTS = [
  { id:"first",icon:"★",title:"First Trick",text:"Complete your first lesson." },{ id:"bower",icon:"♛",title:"Bower Spotter",text:"Master both bowers." },{ id:"bidder",icon:"📣",title:"Confident Caller",text:"Master both bidding rounds." },{ id:"team",icon:"🤝",title:"Perfect Partner",text:"Complete both partner-play lessons." },{ id:"streak",icon:"⚡",title:"Hot Streak",text:"Answer three challenges correctly in a row." },{ id:"mini",icon:"♣",title:"Trick Taker",text:"Complete the Mini Mission." },{ id:"table",icon:"🏆",title:"Roundhouse Regular",text:"Complete a full AI hand." }
];
let progress=loadProgress(),screen="home",currentLevel=1,lessonState={},handState=null;
function loadProgress(){const f={xp:0,completed:[],stars:{},achievements:[],streak:0,bestStreak:0};try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return v&&typeof v==="object"?{...f,...v}:f;}catch{return f;}}
function saveProgress(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));}catch{}}
function showToast(text){toast.textContent=text;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,2200);}
function render(){if(screen==="home")renderHome();else if(screen==="level")renderLevel();else if(screen==="achievements")renderAchievements();else renderHand();app.focus({preventScroll:true});scrollTo(0,0);}
function hud(){return `<section class="hud"><div><span>Level</span><strong>${Math.min(LEVELS.length,1+progress.completed.length)}</strong></div><div><span>XP</span><strong>${progress.xp}</strong></div><div><span>Lessons</span><strong>${progress.completed.length}/${LEVELS.length}</strong></div><div><span>Best streak</span><strong>${progress.bestStreak}</strong></div></section><div class="progress"><span style="width:${Math.min(100,progress.xp%100)}%"></span></div>`;}
function renderHome(){const chars=window.ROUNDHOUSE_CHARACTERS.slice(0,4);app.innerHTML=`<p class="eyebrow">The Roundhouse Card Academy</p><h1>Euchre at the Roundhouse</h1><p class="lede">Learn Euchre in tiny missions: trump, bowers, the Benny, bidding, scoring and clever partner play.</p>${hud()}<div class="portrait-strip">${chars.map(c=>`<img src="../poison/${c.image}" alt="${c.name}">`).join("")}</div><div class="actions"><button data-action="continue">${progress.completed.length?"Continue academy":"Start learning"}</button><button class="secondary" data-action="achievements">Achievements</button></div><section class="level-grid">${LEVELS.map(levelCard).join("")}</section><p class="mini-rule">4 players in two partnerships. Cards 9 through Ace plus the Joker Benny. Benny, Right Bower, Left Bower, A, K, Q, 10, 9.</p>`;app.querySelector('[data-action="continue"]').onclick=()=>openLevel(Math.min(LEVELS.length,progress.completed.length+1));app.querySelector('[data-action="achievements"]').onclick=()=>{screen="achievements";render();};app.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>openLevel(+b.dataset.level));}
function levelCard(l){const u=l.id<=progress.completed.length+1,c=progress.completed.includes(l.id),s=progress.stars[l.id]||0;return `<button class="level-card ${u?"unlocked":"locked"} ${c?"completed":""}" data-level="${l.id}" ${u?"":"disabled"}><span class="badge">Mission ${l.id}</span><h3>${l.title}</h3><p>${l.subtitle}</p><div class="stars">${c?"★".repeat(s)+"☆".repeat(3-s):u?"Ready":"Locked"}</div></button>`;}
function openLevel(id){currentLevel=id;lessonState={attempts:0,correct:0,answered:false};if(LEVELS[id-1].kind==="full"){startFullHand();return;}screen="level";render();}
function renderLevel(){const l=LEVELS[currentLevel-1];app.innerHTML=`<div class="lesson"><p class="eyebrow">Mission ${l.id} of ${LEVELS.length}</p><h1>${l.title}</h1><p class="lede">${l.subtitle}</p>${lessonContent(l.kind)}<div class="actions"><button class="ghost" data-home>Back to academy</button></div></div>`;app.querySelector("[data-home]").onclick=()=>{screen="home";render();};bindLesson(l.kind);}
const C=(rank,suit,joker=false)=>({rank,suit,joker});
function lessonContent(k){
 if(k==="pack")return cardQuiz("Which group shows cards that are all used in our Roundhouse Euchre pack?",[[C("2","♣")],[C("9","♣"),C("A","♠"),C("B","★",true)],[C("7","♥"),C("Q","♦"),C("K","♠")]],1,"We use 9, 10, J, Q, K and A in every suit, plus the Joker Benny: 25 cards.");
 if(k==="trump")return cardQuiz("Hearts are trump. These three cards are in the same trick. Which one wins?",[[C("A","♣")],[C("9","♥")],[C("K","♣")]],1,"Any trump beats any non-trump card.");
 if(k==="right")return cardQuiz("Clubs are trump. Which of these is the strongest ordinary card?",[[C("A","♣")],[C("J","♣")],[C("J","♠")]],1,"The Jack of trump is the Right Bower. Only the Benny beats it.");
 if(k==="left")return cardQuiz("Hearts are trump. Which printed Diamond now counts as a Heart?",[[C("J","♦")],[C("A","♦")],[C("Q","♦")]],0,"The same-colour Jack becomes the Left Bower and counts as trump.");
 if(k==="benny")return cardQuiz("Hearts are trump. Which card is higher than the Right Bower J♥?",[[C("A","♥")],[C("B","★",true)],[C("J","♦")]],1,"The Benny is the Joker and the highest trump card.");
 if(k==="follow")return cardQuiz("Clubs were led. Your full hand is 9♣, A♥ and K♠. Which card are you required to play?",[[C("9","♣")],[C("A","♥")],[C("K","♠")]],0,"If you can follow suit, you must.");
 if(k==="winner")return cardQuiz("Spades are trump. The trick contains A♥, 9♠ and A♣. Which card wins?",[[C("A","♥")],[C("9","♠")],[C("A","♣")]],1,"Even the 9 of trump beats every off-suit Ace.");
 if(k==="tactics")return cardQuiz("Clubs were led and your partner's A♣ is currently winning. You hold exactly 9♣ and J♥, with Hearts trump. Which is the best play?",[[C("J","♥")],[C("9","♣")]],1,"You must follow Clubs, and the 9♣ also saves your powerful trump.");
 if(k==="orderup")return choiceQuiz("Dealer turns up K♥. Your hand is J♥, J♦, A♥, 10♣, 9♠. In the first bidding round, what is the best call?",["Order it up: Hearts are trump","Pass","Call Clubs"],0,"Round one only lets you accept the turned-up suit. With both bowers and the Ace, Hearts is overwhelmingly strong.");
 if(k==="dealerpick")return choiceQuiz("You are not the dealer and you order up the turned K♥. What happens to that card?",["It stays in the kitty","The dealer picks it up and discards one card","You take it into your own hand"],1,"Ordering up makes the dealer pick up the face-up card and discard one card.");
 if(k==="roundtwo")return choiceQuiz("Everyone passes in round one on the turned-up Hearts. Which statement about round two is correct?",["Players may call Clubs, Diamonds or Spades as trump","Hearts is still the only suit that may be called","The hand must always be redealt"],0,"In round two, the turned suit is rejected and players may name a different suit as trump.");
 if(k==="alone")return cardQuiz("You call Hearts. Which complete five-card hand is clearly strong enough to consider going alone?",[[C("B","★",true),C("J","♥"),C("J","♦"),C("A","♥"),C("K","♥")],[C("9","♣"),C("10","♦"),C("Q","♠"),C("9","♠"),C("10","♣")]],0,"Going alone means your partner sits out. A hand containing the top five trump is an obvious lone-hand candidate.");
 if(k==="scoring")return choiceQuiz("Using our Roundhouse scoring: makers take 3 tricks; makers take all 5; a lone maker takes all 5; makers take only 2. Which scores are correct in that order?",["1, 2, 4, defenders 2","2, 1, 4, defenders 1","1, 4, 2, defenders 2"],0,"Make the contract for 1; sweep for 2; lone sweep for 4. If makers take fewer than 3, defenders score 2: a euchre.");
 if(k==="partner")return cardQuiz("Spades were led and are not trump. Your partner's K♠ is currently winning. You hold exactly A♠ and 9♠. Which is the better team play?",[[C("A","♠")],[C("9","♠")]],1,"Both cards are legal, but the 9♠ is the clearly better tactical play because it lets your partner keep the trick and saves the Ace.");
 if(k==="partnerlead")return cardQuiz("You are on lead. Your partner called Hearts and you hold exactly 9♥, A♣ and K♦. Which lead best supports a strong trump-calling partner?",[[C("9","♥")],[C("A","♣")],[C("K","♦")]],0,"Leading a small trump can help draw enemy trump when your partner has called Hearts and is expected to be strong there.");
 if(k==="mini")return `<div class="lesson-box"><h2>Partner Challenge</h2><p>Choose the best team play in each situation. More than one card may be legal, but only one is the intended tactical choice.</p><div id="mini-game"></div></div>`;return "";
}
function choiceQuiz(q,o,c,t){return `<section class="question"><h2>${q}</h2><div class="answers">${o.map((x,i)=>`<button class="answer" data-answer="${i}">${x}</button>`).join("")}</div><p class="tip">${t}</p><div id="feedback"></div></section>`;}
function cardQuiz(q,groups,c,t){return `<section class="question"><h2>${q}</h2><div class="card-answers">${groups.map((g,i)=>`<button class="card-answer" data-answer="${i}">${g.map(cardHtml).join("")}</button>`).join("")}</div><p class="tip">${t}</p><div id="feedback"></div></section>`;}
function bindLesson(k){if(k==="mini"){startMiniMission();return;}app.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>answerQuiz(+b.dataset.answer,({pack:1,trump:1,right:1,left:0,benny:1,follow:0,winner:1,tactics:1,orderup:0,dealerpick:1,roundtwo:0,alone:0,scoring:0,partner:1,partnerlead:0})[k]));}
function answerQuiz(i,c){if(lessonState.answered)return;lessonState.attempts++;if(i!==c){progress.streak=0;app.querySelector("#feedback").innerHTML=`<p class="feedback">Not quite. Try again—there's no penalty.</p>`;showToast("Try another answer");saveProgress();return;}lessonState.answered=true;progress.streak++;progress.bestStreak=Math.max(progress.bestStreak,progress.streak);if(progress.streak>=3)unlockAchievement("streak");app.querySelectorAll("[data-answer]").forEach((b,n)=>{b.disabled=true;if(n===c)b.classList.add("correct");});app.querySelector("#feedback").innerHTML=`<p class="feedback">Correct! Nice work.</p><div class="actions"><button data-complete>Mission complete</button></div>`;app.querySelector("[data-complete]").onclick=completeCurrentLevel;saveProgress();}
function completeCurrentLevel(starsOverride){const l=LEVELS[currentLevel-1];if(!progress.completed.includes(l.id)){progress.completed.push(l.id);progress.xp+=l.xp;}progress.stars[l.id]=Math.max(progress.stars[l.id]||0,starsOverride||(lessonState.attempts<=1?3:lessonState.attempts<=2?2:1));if(l.id===1)unlockAchievement("first");if(progress.completed.includes(3)&&progress.completed.includes(4))unlockAchievement("bower");if(progress.completed.includes(9)&&progress.completed.includes(11))unlockAchievement("bidder");if(progress.completed.includes(14)&&progress.completed.includes(15))unlockAchievement("team");if(l.kind==="mini")unlockAchievement("mini");saveProgress();showToast(`Mission complete · +${l.xp} XP`);screen="home";render();}
function unlockAchievement(id){if(progress.achievements.includes(id))return;progress.achievements.push(id);saveProgress();const a=ACHIEVEMENTS.find(x=>x.id===id);if(a)showToast(`Achievement: ${a.title}`);}
function renderAchievements(){app.innerHTML=`<p class="eyebrow">Trophy cabinet</p><h1>Achievements</h1>${hud()}<section class="achievement-grid">${ACHIEVEMENTS.map(a=>`<article class="achievement ${progress.achievements.includes(a.id)?"unlocked":"locked"}"><div class="icon">${a.icon}</div><h3>${a.title}</h3><p>${a.text}</p><span class="badge">${progress.achievements.includes(a.id)?"Unlocked":"Locked"}</span></article>`).join("")}</section><div class="actions"><button data-home>Back</button></div>`;app.querySelector("[data-home]").onclick=()=>{screen="home";render();};}
function startMiniMission(){const rounds=[{text:"Clubs were led. Partner's A♣ is winning. Your hand is 9♣ and J♥ (Hearts trump). Choose the best play.",hand:[C("9","♣"),C("J","♥")],correct:0},{text:"You are on lead. Partner called Hearts. Your hand is 9♥ and A♣. Choose the best supporting lead.",hand:[C("9","♥"),C("A","♣")],correct:0},{text:"Spades were led and aren't trump. Partner's K♠ is winning. You hold A♠ and 9♠. Choose the better team play.",hand:[C("A","♠"),C("9","♠")],correct:1}];lessonState.miniIndex=0;lessonState.correct=0;renderMiniRound(rounds);}
function renderMiniRound(rounds){const box=app.querySelector("#mini-game");if(lessonState.miniIndex>=rounds.length){box.innerHTML=`<p class="feedback">You made ${lessonState.correct}/3 good team plays.</p><div class="actions"><button data-finish>Finish mission</button></div>`;box.querySelector("[data-finish]").onclick=()=>completeCurrentLevel(lessonState.correct===3?3:2);return;}const r=rounds[lessonState.miniIndex];box.innerHTML=`<p class="tip">${r.text}</p><div class="card-answers">${r.hand.map((c,i)=>`<button class="card-answer" data-mini="${i}">${cardHtml(c)}</button>`).join("")}</div>`;box.querySelectorAll("[data-mini]").forEach(b=>b.onclick=()=>{const good=+b.dataset.mini===r.correct;if(good){lessonState.correct++;showToast("Smart team play!");}else showToast("Legal perhaps, but not the best team play here.");lessonState.miniIndex++;renderMiniRound(rounds);});}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;}
function buildDeck(){const d=[];SUITS.forEach(s=>RANKS.forEach(r=>d.push(C(r,s))));d.push(C("B","★",true));return d;}
function sameColour(a,b){return RED.has(a)===RED.has(b);}
function effectiveSuit(card,trump){if(card.joker)return trump;if(card.rank==="J"&&card.suit!==trump&&sameColour(card.suit,trump))return trump;return card.suit;}
function strength(card,trump,led){if(card.joker)return 100;if(card.rank==="J"&&card.suit===trump)return 99;if(card.rank==="J"&&card.suit!==trump&&sameColour(card.suit,trump))return 98;const order={"9":1,"10":2,"Q":3,"K":4,"A":5,"J":6};const s=effectiveSuit(card,trump);if(s===trump)return 70+order[card.rank];if(s===led)return 30+order[card.rank];return order[card.rank];}
function legalCards(hand,led,trump){if(!led)return hand;const f=hand.filter(c=>effectiveSuit(c,trump)===led);return f.length?f:hand;}
function cardHtml(c){if(c.joker)return `<span class="playing-card joker"><span class="corner">JOKER</span><img src="${BENNY_PORTRAIT}" alt="Roundhouse Joker"><span class="joker-banner">BENNY</span><span class="joker-star">★</span></span>`;const red=RED.has(c.suit),face=["J","Q","K"].includes(c.rank);let img="";if(face){const idx=SUITS.indexOf(c.suit),id=FACE_PORTRAITS[c.rank][idx];img=`<img src="../poison/assets/portraits/${id}.png" alt="Roundhouse ${c.rank}">`;}return `<span class="playing-card ${red?"red":""} ${face?"face":""}"><span class="corner">${c.rank}<br>${c.suit}</span>${img}<span class="suit">${c.suit}</span></span>`;}
function startFullHand(){const deck=shuffle(buildDeck()),hands=[[],[],[],[]];for(let r=0;r<5;r++)for(let p=0;p<4;p++)hands[p].push(deck.pop());let best=SUITS[0],score=-1;SUITS.forEach(s=>{const v=hands[0].reduce((n,c)=>n+strength(c,s,s),0);if(v>score){score=v;best=s;}});handState={hands,trump:best,leader:0,trick:[],tricks:[0,0],number:1,message:`Your strongest suit is ${best}, so it is trump for this training hand. You and Margot are partners.`};screen="hand";render();}
function renderHand(){const h=handState;if(h.number>5||h.hands.every(x=>x.length===0)){finishFullHand();return;}const chars=window.ROUNDHOUSE_CHARACTERS.slice(4,8);app.innerHTML=`<p class="eyebrow">Final Mission · Trick ${h.number} of 5</p><h1>Roundhouse Table</h1><div class="score-banner">Trump ${h.trump} · You & Margot ${h.tricks[0]} — Opponents ${h.tricks[1]}</div><p class="lede">${h.message}</p><section class="table"><div class="trick-grid">${[0,1,2,3].map(i=>`<div class="seat ${i===0?"you":""}"><img src="../poison/${chars[i].image}" alt="${chars[i].name}"><strong>${i===0?"You":chars[i].name}</strong><div>${h.trick.find(x=>x.player===i)?cardHtml(h.trick.find(x=>x.player===i).card):"Waiting"}</div></div>`).join("")}</div></section><h2>Your hand</h2><div class="hand">${h.hands[0].map((c,i)=>`<button class="card-pick" data-card="${i}">${cardHtml(c)}</button>`).join("")}</div><p class="tip">You must follow suit when able. Illegal cards are disabled.</p>`;playUntilHuman();}
function playUntilHuman(){const h=handState;if(h.trick.length>=4){settleTrick();return;}const player=(h.leader+h.trick.length)%4;if(player===0){const led=h.trick.length?effectiveSuit(h.trick[0].card,h.trump):null,legal=legalCards(h.hands[0],led,h.trump);app.querySelectorAll("[data-card]").forEach(b=>{const c=h.hands[0][+b.dataset.card];b.disabled=!legal.includes(c);b.onclick=()=>playCard(0,+b.dataset.card);});return;}const led=h.trick.length?effectiveSuit(h.trick[0].card,h.trump):null,legal=legalCards(h.hands[player],led,h.trump),pick=legal.reduce((best,c)=>strength(c,h.trump,led)<strength(best,h.trump,led)?c:best,legal[0]),idx=h.hands[player].indexOf(pick);playCard(player,idx);}
function playCard(player,index){const h=handState,card=h.hands[player].splice(index,1)[0];h.trick.push({player,card});render();}
function settleTrick(){const h=handState,led=effectiveSuit(h.trick[0].card,h.trump);let winner=h.trick[0];h.trick.forEach(x=>{if(strength(x.card,h.trump,led)>strength(winner.card,h.trump,led))winner=x;});h.tricks[winner.player%2]++;h.leader=winner.player;h.message=`${winner.player===0?"You":window.ROUNDHOUSE_CHARACTERS.slice(4,8)[winner.player].name} won the trick.`;h.trick=[];h.number++;setTimeout(render,650);}
function finishFullHand(){const won=handState.tricks[0]>=3;if(!progress.completed.includes(17)){progress.completed.push(17);progress.xp+=120;progress.stars[17]=won?3:2;}unlockAchievement("table");saveProgress();app.innerHTML=`<p class="eyebrow">Academy complete</p><h1>${won?"You won the hand!":"Hand complete"}</h1><p class="lede">Final score: your team ${handState.tricks[0]}, opponents ${handState.tricks[1]}. ${won?"Excellent—you are ready for a real table.":"You finished a full legal hand. Replay it and try for three tricks."}</p><div class="actions"><button data-home>Return to academy</button></div>`;app.querySelector("[data-home]").onclick=()=>{screen="home";render();};}
render();